services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  flask:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql
      MYSQL_DATABASE: todo_bd
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  mysql-data:
