version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    restart: always
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URI: mysql+pymysql://user:password@db/todo_db
    depends_on:
      - db

volumes:
  db_data:
